/**
 * Debug Test for CodeBlock HTML Rendering
 */

'use client';

import { useState } from 'react';
import { CodeBlock } from '@/components/docs/CodeBlock';

function DebugCodeBlock({ code, language = 'bash' }: { code: string; language?: string }) {
  const [showRaw, setShowRaw] = useState(false);

  // Simple highlight function for testing
  function simpleHighlight(text: string): string {
    let result = text
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    if (language === 'bash') {
      // Only highlight comments that start with # (not URLs)
      result = result.replace(/(^|\s)(#.*$)/gm, '$1<span style="color: #6b7280;">$2</span>');
      // Highlight strings
      result = result.replace(/(['"])((?:\\.|(?!\1).)*?)\1/g, '<span style="color: #34d399;">$1$2$1</span>');
      // Highlight common commands
      result = result.replace(/\b(curl|wget|git|echo|cd)\b/g, '<span style="color: #a78bfa;">$1</span>');
    }

    return result;
  }

  const highlighted = simpleHighlight(code);

  return (
    <div className="my-6">
      <div className="flex gap-4 mb-2">
        <button
          onClick={() => setShowRaw(!showRaw)}
          className="px-3 py-1 bg-blue-500 text-white rounded text-sm"
        >
          {showRaw ? 'Show Rendered' : 'Show Raw HTML'}
        </button>
        <span className="text-sm text-gray-400">Language: {language}</span>
      </div>

      <div className="bg-gray-900 p-4 rounded-lg">
        {showRaw ? (
          <pre className="text-xs text-green-400 whitespace-pre-wrap break-all">
            {highlighted}
          </pre>
        ) : (
          <pre>
            <code dangerouslySetInnerHTML={{ __html: highlighted }} />
          </pre>
        )}
      </div>
    </div>
  );
}

export default function DebugTestPage() {
  const bashCode1 = `# This is a comment
curl https://example.com/api
echo "Hello World"`;

  const bashCode2 = `git clone https://github.com/user/repo.git
cd repo
npm install`;

  const bashCode3 = `# Download from https://example.com
wget "https://example.com/file.tar.gz"
tar -xzf file.tar.gz`;

  return (
    <div className="docs-content max-w-4xl mx-auto py-8">
      <h1 className="text-4xl font-bold mb-8">Debug Test - CodeBlock HTML Rendering</h1>

      <p className="mb-6 text-gray-400">
        Click "Show Raw HTML" to see the actual HTML being generated by the syntax highlighter.
        This will help identify if span tags are being generated correctly.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Test 1: Comment and URL</h2>
      <DebugCodeBlock code={bashCode1} language="bash" />

      <h2 className="text-2xl font-semibold mb-4">Test 2: Git Commands</h2>
      <DebugCodeBlock code={bashCode2} language="bash" />

      <h2 className="text-2xl font-semibold mb-4">Test 3: URLs in Strings</h2>
      <DebugCodeBlock code={bashCode3} language="bash" />

      <h2 className="text-2xl font-semibold mb-4">Test 4: Plain Text (No Highlighting)</h2>
      <DebugCodeBlock code={bashCode1} language="text" />

      <div className="mt-12 p-6 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
        <h3 className="font-bold mb-2">What to Check:</h3>
        <ul className="space-y-2 text-sm">
          <li>• URLs should NOT have span tags around the // part</li>
          <li>• Comments (lines starting with #) should be wrapped in gray spans</li>
          <li>• Strings should be wrapped in green spans</li>
          <li>• Commands should be wrapped in purple spans</li>
          <li>• The "Show Raw HTML" view should show &lt;span&gt; tags</li>
          <li>• The "Show Rendered" view should show colored text, NOT visible span tags</li>
        </ul>
      </div>

      <h2 className="text-2xl font-semibold mb-4 mt-12">Comparison with Actual CodeBlock Component</h2>

      <h3 className="text-xl font-semibold mb-4">Actual CodeBlock - Bash with URLs</h3>
      <CodeBlock
        code={`# Install dependencies
curl https://example.com/install.sh | bash
wget "https://github.com/user/repo/archive.tar.gz"
git clone https://github.com/user/repo.git`}
        language="bash"
      />

      <h3 className="text-xl font-semibold mb-4">Actual CodeBlock - With Line Numbers</h3>
      <CodeBlock
        code={bashCode1}
        language="bash"
        showLineNumbers={true}
      />
    </div>
  );
}