[build]
builder = "nixpacks"
buildCommand = "bun install"

[build.nixpacks]
bun_version = "1.1"

[deploy]
startCommand = "bun run scripts/railway-start.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=1024"
TRUST_PROXY = "true"
EXPRESS_TRUST_PROXY = "true"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "staging"
NODE_OPTIONS = "--max-old-space-size=1024"
TRUST_PROXY = "true"
EXPRESS_TRUST_PROXY = "true"

# Railway automatically handles:
# - PORT environment variable
# - DATABASE_URL with proper SSL
# - Auto-scaling and health checks